### ISSUE TITLE
Tests are failing in Julia 1.10

### ISSUE THREAD

**Issue by bvdmitri** [ReactiveBayes/FastCholesky.jl#11]
See for example [this](https://github.com/ReactiveBayes/FastCholesky.jl/actions/runs/7503591536/job/20428669390)

**Comment by bvdmitri** [comment]
This could have potentially caused the issue with the continuous transition node in ReactiveMP here https://github.com/ReactiveBayes/ReactiveMP.jl/pull/372

**Comment by bartvanerp** [comment]
Corresponding test seems to check inversion of a very bad matrix, so I am not entirely surprised about just exceeding the tolerances. Robustness in the test could be improved anyways. Instead of computing `inv(A)*B` you should always call `A/B`.

**Comment by bartvanerp** [comment]
Might also be related to `PostiveFactorizations` that we use as a fallback. Not sure whether it uses that one in the test case, but will check later.

**Comment by bartvanerp** [comment]
It has to do with our own fastcholesky implementation, but I can't reproduce this on my Mac, so it seems to be system-dependent. @bvdmitri I propose to just increase tolerances.

**Comment by bvdmitri** [comment]
Couldn't reproduce it on my mac either. I've adjusted the tests a bit
